//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OddsScraper.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OddsScraper.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///&lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot; lang=&quot;de-DE&quot; prefix=&quot;og: http://ogp.me/ns#&quot;&gt;
        ///&lt;head profile=&quot;http://gmpg.org/xfn/11&quot;&gt;
        ///&lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot; /&gt;
        ///&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot; /&gt;
        ///&lt;title&gt;EM 2016 Spielplan » alle Spiele, Termine und Wettquoten &lt;/title&gt;
        ///&lt;link rel=&quot;pingback&quot; href=&quot;http://www.wettfreunde.net/xm [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EMTippspiel {
            get {
                return ResourceManager.GetString("EMTippspiel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///&lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot; lang=&quot;de-DE&quot; prefix=&quot;og: http://ogp.me/ns#&quot;&gt;
        ///&lt;head profile=&quot;http://gmpg.org/xfn/11&quot;&gt;
        ///&lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot; /&gt;
        ///&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot; /&gt;
        ///&lt;title&gt;EM 2016 Spielplan » alle Spiele, Termine und Wettquoten &lt;/title&gt;
        ///&lt;link rel=&quot;pingback&quot; href=&quot;http://www.wettfreunde.net/xm [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EMTippspiel_Achtelfinals {
            get {
                return ResourceManager.GetString("EMTippspiel_Achtelfinals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///&lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot; lang=&quot;de-DE&quot; prefix=&quot;og: http://ogp.me/ns#&quot;&gt;
        ///&lt;head profile=&quot;http://gmpg.org/xfn/11&quot;&gt;
        ///&lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot; /&gt;
        ///&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot; /&gt;
        ///&lt;title&gt;EM 2016 Spielplan » alle Spiele, Termine und Wettquoten &lt;/title&gt;
        ///&lt;link rel=&quot;pingback&quot; href=&quot;http://www.wettfreunde.net/xm [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EMTippspiel_Final {
            get {
                return ResourceManager.GetString("EMTippspiel_Final", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///&lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot; lang=&quot;de-DE&quot; prefix=&quot;og: http://ogp.me/ns#&quot;&gt;
        ///&lt;head profile=&quot;http://gmpg.org/xfn/11&quot;&gt;
        ///&lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot; /&gt;
        ///&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot; /&gt;
        ///&lt;title&gt;EM 2016 Spielplan » alle Spiele, Termine und Wettquoten &lt;/title&gt;
        ///&lt;link rel=&quot;pingback&quot; href=&quot;http://www.wettfreunde.net/xm [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EMTippspiel_Viertelfinals {
            get {
                return ResourceManager.GetString("EMTippspiel_Viertelfinals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot; lang=&quot;de-DE&quot; prefix=&quot;og: http://ogp.me/ns#&quot;&gt;
        ///
        ///&lt;head profile=&quot;http://gmpg.org/xfn/11&quot;&gt;
        ///
        ///&lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot;&gt;
        ///
        ///&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot;&gt;
        ///
        ///&lt;meta name=&quot;google-site-verification&quot; content=&quot;I7oYBju5U8mGS3gg7ok3wn2Ez8Mtom7AhW89QKSa_tk&quot;&gt;
        ///
        ///&lt;title&gt;Bundesliga Spielplan 2017/2018 - Spiele, Termine, Wettquoten &amp;raquo; wettfreunde.net &lt;/title&gt;
        ///
        ///
        ///
        ///
        ///
        ///&lt;meta name=&quot;description&quot; content=&quot;Spie [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string spieltag14 {
            get {
                return ResourceManager.GetString("spieltag14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///&lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;de-DE&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;!-- Google Tag Manager --&gt;
        ///    &lt;script&gt;(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({&apos;gtm.start&apos;:
        ///          new Date().getTime(),event:&apos;gtm.js&apos;});var f=d.getElementsByTagName(s)[0],
        ///        j=d.createElement(s),dl=l!=&apos;dataLayer&apos;?&apos;&amp;l=&apos;+l:&apos;&apos;;j.async=true;j.src=
        ///        &apos;https://www.googletagmanager.com/gtm.js?id=&apos;+i+dl;f.parentNode.insertBefore(j,f);
        ///      })(window,document,&apos;script&apos;,&apos;dataLayer&apos;,&apos;GTM-KCQTLCV&apos;);&lt;/script&gt;
        ///    &lt;!-- End Google Tag Manager [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string spieltag2019_2 {
            get {
                return ResourceManager.GetString("spieltag2019_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///&lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot; lang=&quot;de-DE&quot; prefix=&quot;og: http://ogp.me/ns#&quot;&gt;
        ///&lt;head profile=&quot;http://gmpg.org/xfn/11&quot;&gt;
        ///&lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot; /&gt;
        ///&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot; /&gt;
        ///&lt;meta name=&quot;google-site-verification&quot; content=&quot;I7oYBju5U8mGS3gg7ok3wn2Ez8Mtom7AhW89QKSa_tk&quot; /&gt;
        ///&lt;title&gt;Bundesliga Spielplan 2017/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Spieltag23Html {
            get {
                return ResourceManager.GetString("Spieltag23Html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///&lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot; lang=&quot;de-DE&quot; prefix=&quot;og: http://ogp.me/ns#&quot;&gt;
        ///&lt;head profile=&quot;http://gmpg.org/xfn/11&quot;&gt;
        ///&lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot; /&gt;
        ///&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot; /&gt;
        ///&lt;title&gt;Bundesliga Spielplan 2015/2016 - Spiele, Termine, Wettquoten &amp;raquo; wettfreunde.net &lt;/title&gt;
        ///&lt;link rel=&quot;pingback&quot; href=&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Spieltag26Html {
            get {
                return ResourceManager.GetString("Spieltag26Html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///&lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot; lang=&quot;de-DE&quot; prefix=&quot;og: http://ogp.me/ns#&quot;&gt;
        ///&lt;head profile=&quot;http://gmpg.org/xfn/11&quot;&gt;
        ///&lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot; /&gt;
        ///&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot; /&gt;
        ///&lt;title&gt;Bundesliga Spielplan 2016/2017 - Spiele, Termine, Wettquoten &amp;raquo; wettfreunde.net &lt;/title&gt;
        ///&lt;link rel=&quot;pingback&quot; href=&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Spieltag3Html {
            get {
                return ResourceManager.GetString("Spieltag3Html", resourceCulture);
            }
        }
    }
}
